### ISSUE TITLE
Media embed does not work with document-list

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11386]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing`
2. Create a few list items
3. In one of the middle list items press `shift` + `enter` a couple of times 
4. Try to put Media embed into free place between list elements

### ✔️ Expected result

Media embed does not break document list and become part of one of list elements.

### ❌ Actual result

Media embed breaks the list and is not within any list element:
![document list media embed issue](https://user-images.githubusercontent.com/32898551/156419348-1dd83272-0fef-4fe8-8a9d-1ff5f4143ac6.gif)

## 📃 Other details

* Browser: Chrome, Firefox
* OS: Mac OS Monterey
* First affected CKEditor version: 32.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Fixed on latest `ck/11198-make-sure-list-isnt-split`.

**Comment by dufipl** [comment]
Media embed works correctly in a document list only when it is created within a list. When it is created outside of it, it is still not working with the document list:
![media embed issue document list](https://user-images.githubusercontent.com/32898551/161261021-e91e15eb-9a50-4283-9f0d-a8c505d87e20.gif)

**Comment by oleq** [comment]
Closed in #11425.
