### ISSUE TITLE
Cannot build custom editor using plugin defined with relative path in package.json

### ISSUE THREAD

**Issue by elliarbtan** [ckeditor/ckeditor5#1335]
I run into following problem while using git ckeditor5-block-quote as a base for a custom plugin in ckeditor5-build-decoupled-document

## Is this a bug report or feature request? (choose one)

🐞 Bug report (i think)

## 💻 Version of CKEditor

@ckeditor/ckeditor5-build-decoupled-document  11.1.1

## 📋 Steps to reproduce

1. clone @ckeditor/ckeditor5-build-decoupled-document
2. clone @ckeditor/ckeditor5-block-quote
3. in ./ckeditor5-build-decoupled-document/package.json dev dependencies, 
replace 

> "@ckeditor/ckeditor5-block-quote": "^10.1.0",

with

> "@ckeditor/ckeditor5-block-quote": "file:../ckeditor5-block-quote",

3. `cd ckeditor5-build-decoupled-document`
4. `npm install`
5. `webpack --mode development`
6. test with ` chromium index.html`

with index.html content beeing:

```
<html>
  <head><title>ckeditor build simple test</title></head>
  <body>
    <script src="build/ckeditor.js"></script>
    <div id="toolbar-container"></div>
    <div id="editor"></div>
    <script>
      document.addEventListener("DOMContentLoaded", function(event) { 
      DecoupledEditor.create( document.querySelector( '#editor' ) ).then( editor => {
      const toolbarContainer = document.querySelector( '#toolbar-container' );
      toolbarContainer.appendChild( editor.ui.view.toolbar.element );
      } )
      .catch( error => {
      console.error( error );
      } );
});

  </script>
  </body>
</html>

```

## ✅ Expected result

same as @ckeditor/ckeditor5-build-decoupled-document build : editor working.

## ❎ Actual result

error in console

> TypeError: writer.createRangeIn is not a function
>     at editor.model.document.registerPostFixer.writer (blockquoteediting.js:71)
>     at Document._callPostFixers (document.js:369)
>     at Model.Document.listenTo (document.js:161)
>     at Model.fire (emittermixin.js:196)
>     at Model._runPendingChanges (model.js:500)
>     at Model.enqueueChange (model.js:205)
>     at DataController.init (datacontroller.js:203)
>     at DataController.on (observablemixin.js:249)
>     at DataController.fire (emittermixin.js:196)
>     at DataController.(anonymous function) [as init] (file:///path/to/ckeditor5-build-decoupled-document/build/ckeditor.js:117899:16)
> 

## 📃 Other details that might be useful

Or do I miss something important ?

**Comment by Reinmar** [comment]
You should use `stable` branches of all those repositories that you want to test. I can see in the stack trace that you used `master` because of `writer.createRangeIn()` which I merged yesterday. It's not available in the version of ckeditor5-engine which is available on npm so that's why it's broken.

**Comment by elliarbtan** [comment]
Thanks a lot for the answer.

Using `stable` branch, the editor now loads with no visible error but still does not behave correctly. For instance, if i type a character then click on the `italics` button, the following string is added to the text :

> â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹â€‹

Selecting this text, the following message appears in console :

```
ckeditorerror.js:46 Uncaught i: view-renderer-filler-was-lost: The inline filler node was lost. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-renderer-filler-was-lost

    at Gi._removeInlineFiller (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:177886)
    at Gi.render (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:175950)
    at Ns._render (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:209725)
    at Ns.on (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:207668)
    at Ns.fire (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:110206)
    at Ns.change (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:209518)
    at Ns.render (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:209549)
    at Bc.listenTo (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:257014)
    at Bc.fire (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:110206)
    at Bc._runPendingChanges (file:///home/path/to/stable/branch/ckeditor5-build-decoupled-document/build/ckeditor.js:5:333871)

```

The issue seems to be of the same kind as the previous one. Would it be a good idea to use stable git branch of all plugins I use in my custom build to ensure version homogeneity ?

**Comment by Reinmar** [comment]
That's because you have a wrong encoding on your server or website. It needs to be UTF8.

**Comment by elliarbtan** [comment]
> It needs to be UTF8.

You are right for this part, thanks !

Still, issue remains with the build as soon as I use the `blockquote` button

```
ckeditorerror.js:46 Uncaught Bh: model-position-path-incorrect: Position path must be an array with at least one item. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-position-path-incorrect
 {"path":[]}
    at new Kp (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:446327)
    at Function.createFromPosition (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:452414)
    at Gp._next (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:444288)
    at Gp._next (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:445046)
    at Gp._next (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:445046)
    at Gp.next (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:444228)
    at Zp.getItems (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:454829)
    at getItems.next (<anonymous>)
    at t.model.document.registerPostFixer.n (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:461806)
    at Ac._callPostFixers (file:///home/path/to/stablestables/ckeditor5-build-decoupled-document/build/ckeditor.js:5:319793)

```
Note that this build uses stable git versions of` ckeditor5-build-decoupled-document` and `ckeditor5-block-quote`, and the current npm version for the rest.

**Comment by Reinmar** [comment]
You'd have to create a repository with all that code and explain how to reproduce the bug here, because otherwise we're not able to tell what's going on.

**Comment by elliarbtan** [comment]
No custom code here ! I don't think a repo is need (can provide one if you prefer), here are the steps to reproduce :

```
git clone https://github.com/ckeditor/ckeditor5-block-quote
cd ckeditor5-block-quote/
git branch -u remotes/origin/stable
git checkout stable
cd ..

git clone https://github.com/ckeditor/ckeditor5-build-decoupled-document.git
cd ckeditor5-build-decoupled-document/
git branch -u remotes/origin/stable
git checkout stable
sed -i 's/"@ckeditor\/ckeditor5-block-quote": "^10.1.0"/"@ckeditor\/ckeditor5-block-quote": "file:..\/ckeditor5-block-quote"/' package.json
npm install
npm run build
cd ..
```
I test the build with this `index.html` 
```
<html>
  <head><title>ckeditor build simple test</title></head>
  <body>
    <meta charset="UTF-8"> 
    <script src="ckeditor5-build-decoupled-document/build/ckeditor.js"></script>
    <div id="toolbar-container"></div>
    <div id="editor"></div>
    <script>
    document.addEventListener("DOMContentLoaded", () => {
      DecoupledEditor
          .create(document.querySelector('#editor'))
          .then(editor => document
              .querySelector('#toolbar-container')
              .appendChild(editor.ui.view.toolbar.element))
          .catch(error => console.error(error))
    })
    </script>
  </body>
</html>

```
And get aforementioned errors (or others)

**Comment by elliarbtan** [comment]
Thanks a lot for your time on this issue. 

> However, it would be super annoying to code and create some prototypes inside the  `node_modules`

Sure smells like forbidden perfumes !

Thanks for pointing to the development environment guide. I'm gonna try this way.

**Comment by ma2ciek** [comment]
After setting up the development environment, you should be able to run `mgit exec "git checkout stable"` to check out the `stable` branch on each repository.

**Comment by ma2ciek** [comment]
I'll mark this issue as invalid, as we can't support this way of advanced customization because how the deduplication and the resolution system work in the NPM. But feel free to ask if you find some troubles while developing packages via the dev environment.
