### ISSUE TITLE
Image style "aspect-ratio" not reset when image source changes

### ISSUE THREAD

**Issue by tylertf** [ckeditor/ckeditor5#15179]
## 📝 Provide detailed reproduction steps (if any)

1. insert an image that has a portrait aspect ratio (portrait only because it makes it obvious) via a external URL, eg: https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3374&q=80
2. edit the image URL to point to a different image, with a different aspect ratio, eg: https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3843&q=80
3. Notice that the `aspect-ratio` style on the image tag is still from the first image inserted.

You can do this in the CKEditor demo here: https://ckeditor.com/ckeditor-5/demo/feature-rich/

### ✔️ Expected result

The image aspect ratio should be reset to match the new image URL.

### ❌ Actual result

The aspect ratio is from the original image, and the image is not displayed correctly. It is squished to match the aspect ratio.

### ❓ Possible solution

When the image URL changes, a new aspect ratio should be determined from the updated image.

## 📃 Other details

This is new in the 40.0 release, where the aspect-ratio style was added. Its in the image plugin, in the file imagesizeattributes.ts. The aspect ratio gets set, but nothing ever updates it or removes it as things change. 

The same thing happens if you call the `replaceImageSource` command manually from a custom plugin, which is how I bumped into this initially.

Screenshot the UI I am using:
![Screenshot 2023-10-12 133340](https://github.com/ckeditor/ckeditor5/assets/144932527/98ee8be8-591d-4167-af5c-c9f4c15f07fc)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thank you for the report! We will investigate it asap.

**Comment by Witoso** [comment]
Fixed with the #15093 PR.

**Comment by tylertf** [comment]
Hi @Witoso, did a local build from the nightly release 0.0.0-nightly-20231017.0, which I believe should include the mentioned change, but unfortunately I am still seeing this behaviour with the steps above. Looking at the changes in the PR for #15093, I am not sure that it does fix this issue. I was expecting the PR to remove or update the `aspect-ratio` style applied to images, along with the other attributes that it is removing. Forgive me if I misunderstand.

For reference the build number I am seeing:
![Screenshot 2023-10-17 172105](https://github.com/ckeditor/ckeditor5/assets/144932527/d7b893cf-925d-4ccd-bd29-903174043487)

**Comment by Witoso** [comment]
Confirming, we will recheck.

**Comment by 15852539726** [comment]
> 你好@Witoso，从夜间版本 0.0.0-nightly-20231017.0 进行了本地构建，我认为应该包含上述更改，但不幸的是，通过上述步骤我仍然看到这种行为。[查看#15093](https://github.com/ckeditor/ckeditor5/issues/15093)的 PR 中的更改，我不确定它是否确实解决了这个问题。我期望 PR 删除或更新`aspect-ratio`应用于图像的样式以及它要删除的其他属性。如果我误解了，请原谅我。
> 
> 作为参考，我看到的内部版本号：
> 
> ![截图2023-10-17 172105](https://private-user-images.githubusercontent.com/144932527/276039479-d7b893cf-925d-4ccd-bd29-903174043487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzIyMTMsIm5iZiI6MTcwNjg3MTkxMywicGF0aCI6Ii8xNDQ5MzI1MjcvMjc2MDM5NDc5LWQ3Yjg5M2NmLTkyNWQtNGNjZC1iZDI5LTkwMzE3NDA0MzQ4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxMTA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODgxMWJlMDdkYmY2NjU3YjU1NTE4Y2EwNjA2MDIzOTU4MDhmN2JkNjAwZTlhMzBlM2YxMzMyNTgyMWRlNTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ru6Y24mx6Ysd_fnLu_sJZurWdGCGFGWtuNWIOPPL7vY)

我也发现了同样的问题
