### ISSUE TITLE
Some metadata is retained alongside the content when copying from a Word file on Windows

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15333]
## 📝 Provide detailed reproduction steps (if any)

1. On a Widnows machine copy all of the contents of the attached Word file:

    [CK EDITOR TEST.docx](https://github.com/ckeditor/ckeditor5/files/13308273/CK.EDITOR.TEST.docx)

2. Paste it into the [Paste from Office demo](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office.html#demo) and the [Paste from Office enhanced demo](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html#demo)

### ✔️ Expected result

Only the contents of the file should be copied, as is the case on macOS: 

https://github.com/ckeditor/ckeditor5/assets/72079603/43002dd5-be06-4da6-97c8-5a895838bca7

### ❌ Actual result

On Windows, in the regular PfO demo, some metadata is retained when copying the file:

https://github.com/ckeditor/ckeditor5/assets/72079603/3ed3490c-d66f-414e-b9e3-ac942adf4e86

Whereas in the PfOE demo, the contents of the file do not get copied at all and you can see a `<span>` with the attribute `data-ck-unsafe-element` when you inspect the editable:

https://github.com/ckeditor/ckeditor5/assets/72079603/a0c25e4a-5a7a-42ca-845a-cadb86a7c3ed

### ❓ Possible solution

I'm also including the resulting `text/html` returned by [Clipboard Inpector](https://evercoder.github.io/clipboard-inspector/) when copying and pasting the file on Windows:

[paste_text_html.txt](https://github.com/ckeditor/ckeditor5/files/13308286/paste_text_html.txt)

It's possible that the metadata that is being copied is treated as an HTML comment (it starts with `<!--` and ends with `-->`, so perhaps that's why it's being retained.

## 📃 Other details

* Browser: cross-browser
* OS: Windows 11

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Testing the nightly, looks was fixed by: #14925. Aimed for the next release. Please confirm :)

**Comment by mabryl** [comment]
Unfortunately, this issue is still present on Windows in these demos on nightly docs:

https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/pasting/paste-from-office.html
https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html

The exact same thing happens as in the live documentation.

**Comment by Witoso** [comment]
Ha, thanks! @illia-stv could you check as you have experience in this?
I will mark this actually as a blocker to discuss on the TP summary.

**Comment by mabryl** [comment]
Most likely a related issue can be found in this ticket: https://github.com/ckeditor/ckeditor5/issues/9002
