### ISSUE TITLE
[Docs + Demos] Fix the list of available image styles

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#15773]
## 📝 Provide a description of requested docs changes

The incorrect configuration can be found e.g. here:

*   [https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)
*   [https://ckeditor.com/ckeditor-5/demo/feature-rich/](https://ckeditor.com/ckeditor-5/demo/feature-rich/)
*   and probably many more at this point

The issue can be seen on this screenshot:

![](https://github.com/ckeditor/ckeditor5/assets/156149/798bd569-dc48-48ab-a8d0-7053f53a88c7)

The image toolbar contains 4 buttons:

*   Inline
*   Wrap text (& align)
*   Break text (& align or center)
*   Side image

The last one comes from the "semantic styles" pack and is a duplication of what can be achieved (visually) with "wrap text & align right" button (2nd one). Therefore, "Side image" should be removed from all those samples and their content corrected to use the "wrap text & align right" whenever a side image was used.

**Comment by Witoso** [comment]
When you say _2nd one_, you mean the option under the second's one split button, right? This is what confused me in your messaging :D 

![](https://github.com/ckeditor/ckeditor5/assets/9881379/307dd6ff-edf8-4281-b334-b14fa5ff2aeb)

**Comment by godai78** [comment]
Fixed in #15786

**Comment by Reinmar** [comment]
I can still see this issue in [https://ckeditor.com/ckeditor-5/demo/feature-rich/.](https://ckeditor.com/ckeditor-5/demo/feature-rich/.) 

And in the full featured editor example, the content is incorrect. None of the styles is selected even though the image is aligned to the right, so some style was applied to it. Probably, the markup was manually crafted.

This is how it looks now:

![](https://github.com/ckeditor/ckeditor5/assets/156149/96669e56-44e0-4493-b38a-981332cfe3dc)

This is how it should look like:

![](https://github.com/ckeditor/ckeditor5/assets/156149/ad480eff-16e5-4c46-b25a-11584755dc86)

**Comment by godai78** [comment]
The demo you linked is not the demo you screenshotted, actually.

**Comment by godai78** [comment]
![Screenshot 2024-03-11 at 11 15 56](https://github.com/ckeditor/ckeditor5/assets/68123541/5f67bb07-ec9a-451b-b785-60eea7a7b692)
