### ISSUE TITLE
Word-like list continuation for lists separated by block elements

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#16225]
## 📝 Provide a description of the new feature

In Word, it's possible to create a list that's separated by a block element (e.g. an empty paragraph) that is still one list. The numbering is continued if you add more elements to the list.

Clients who utilize Import from Word or Paste from Office can expect this behavior to also be achievable in CKE5.

Take a look at the recording to see the expected behavior:

https://github.com/ckeditor/ckeditor5/assets/72079603/89a0e7a5-ffa8-4c49-84e2-d1b6297ce698

Related ticket for the doc-converter: https://github.com/cksource/doc-converter/issues/794

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Continuous numbering in Paste from Office was fixed in [**v41.3.0**](https://github.com/ckeditor/ckeditor5/releases/tag/v41.3.0) via #11210.

**Comment by mabryl** [comment]
Some additional context @Witoso 👇 

Yep, the list structure and numbering are retained when pasting from Word but it looks like the editor still doesn't realise that it's supposed to be one list.

If you add some additional items to the first part of the list, the list markers in the second part don't update:

https://github.com/ckeditor/ckeditor5/assets/72079603/02ffcf71-4f8d-4408-81d0-f9e659cf7fcd

In Word, the list teated as one continuous element, which is the functionality that we're looking for in this feature request.

**Comment by Witoso** [comment]
Have you tasted it with PFOE? It has a better detection mechanism based on margins, same release.

**Comment by mabryl** [comment]
Yep, it works the same in regular PfO and in PfOE. The recording in my previous comment is from the enhanced demo.

**Comment by Witoso** [comment]
The heuristic so far is that the paragraph indent needs to be the same as the list item. Otherwise, we cannot detect if such a paragraph is a part of the list.
![image](https://github.com/ckeditor/ckeditor5/assets/9881379/044b72ea-9397-45eb-a2e0-4bab62d52060)

We can keep this open for the future, and to gather interest.

**Comment by melovy** [comment]
Hi @Witoso ,

We attempted the suggested solution regarding paragraph indents aligning with list items. Unfortunately, this hasn't resolved our issue when using "import from Word," nor does it work on the CKEditor "paste from word" online demo. Could you please confirm if this feature has been released and whether it's expected to work with the "import from Word" functionality?

**Comment by Witoso** [comment]
We would need specific examples to test them, but yes improvements for **pasting** are out with a bit different working for Paste from Office and Paste from Office Enhanced, details in docs.

As for the import, @mabryl, do we have an issue for this that details import?

We can treat this ticket as further improvement in this area (although I'm not sure if we have technical possibilities), and gathering interest for this.

**Comment by mabryl** [comment]
@Witoso there's an issue in the internal doc-converter repository that deals with these types of scenarios: https://github.com/cksource/doc-converter/issues/794
