### ISSUE TITLE
Markdown autoformat italics bug

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5#2388]
Sorry if this was fixed in `latest` or not, but I wanted to make to discuss this.

From a user:

> I was writing some notes and tried writing wrote word1_word2_word3 and while writing it, it did word1word2word3 and word 2 was in italics. I am assuming that's because of the underlines but I am not sure this is intentional behavior. Thanks! 

STEPS TO REPRODUCE
1. Type: word_1 and word_2

EXPECTED RESULTS
* word_1 and word_2

ACTUAL RESULTS
* word*1 and word*2

Ref: https://github.com/mozilla/notes/issues/595

I wonder if auto-format should only format if there are spaces around `_` or if it starts the line?

**Comment by DenitsaGencheva** [comment]
Hi guys,
any update on this?
A lot of our clients are complaining because of this issue as they use texts like item_item_item.
We made the following change in the plugin:
this
/(?:^|[^_])(_)([^_]+)(_)$/g
we changed to:
/(?:^|\s)(_)([^_]+)(_)$/g
but this way it is erased after we update the editor.

**Comment by julie0842** [comment]
Hey all, we are running into this issue as well and I just wanted to check to see if there are any updates with this issue? Thanks!

**Comment by Reinmar** [comment]
This works better in GitHub Writer. I think we could make this regexp narrower.

**Comment by maxbarnas** [comment]
#### At this point I checked other Markdown implementations (technical details at the end) and decided to do as below:

*   Simple regex update, that will require a whitespace or punctuation character before opening delimiter should be enough for most cases. 
    *   Considering that Autoformat is mostly an aid in typing, not a full-featured Markdown parser, it does not seem viable to copy the [entire regex for punctuation](https://github.com/commonmark/commonmark.js/blob/master/lib/inlines.js#L39) from CM. Still, I am not sure how far we should go with that - any ideas?
*   Seems reasonable and should be cheap to update Bold functionality in the same manner.
*   Nice-to-have: Autoformat catches cases where first the opening delimiter (`*` or `_`) is typed in, then closing one. Being able to catch a reversed case would be great. 
    *   word → word\_ → \_word\_ ⇒ _word_

#### Most of the above are based on CommonMark [spec](https://spec.commonmark.org/0.29/). Some key elements of that spec:

*   Delimiter: `_` or `*` (single or many).
*   Whitespace: space, tab, the start of the line, end of the line, etc.
*   Punctuation: A punctuation character is an ASCII punctuation character or anything in the general Unicode categories Pc, Pd, Pe, Pf, Pi, Po, or Ps.
*   ASCII punctuation character: `!`, `"`, `#`, `$`, `%`, `&`, `'`, `(`, `)`, `*`, `+`, `,`, `-`, `.`, `/` (U+0021–2F), `:`, `;`, `<`, `=`, `>`, `?`, `@` (U+003A–0040), `[`, `\\`, `]`, `^`, `_`, `(U+005B–0060),`{`,`|`,`}`, or`~\` (U+007B–007E).

**Comment by Reinmar** [comment]
> *   Simple regex update, that will require a whitespace or punctuation character before opening delimiter should be enough for most cases.

What about what's after the closing delimiter?

1.  `aa _bb^cc`
2.  type `_`
3.  aa `_bb_^cc`

It's a less severe case than the one with `foo_bar_^`, but still might be irritating.

> *   Seems reasonable and should be cheap to update Bold functionality in the same manner.

:+1: 

> Nice-to-have: Autoformat catches cases where first the opening delimiter (`*` or `_`) is typed in, then closing one. Being able to catch a reversed case would be great.

This is a nice catch. It always bothered me that it does not work in our implementation of autoformat. If you could check quickly how big that change would be, that'd help us planning this change for the future.

**Comment by maxbarnas** [comment]
> What about what's after the closing delimiter?

Good point. Another reason to treat whitespace as a separator.

Also, in the example below, you can see better why punctuation characters should join whitespace as a separator for autoformat:

1.  word \_word^, word
2.  type `_`
3.  word _word,_ word

**Comment by maxbarnas** [comment]
> This is a nice catch. It always bothered me that it does not work in our implementation of autoformat. If you could check quickly how big that change would be, that'd help us planning this change for the future.

Regarding this, autoformat seems to [grab text from the current line](https://github.com/ckeditor/ckeditor5/blob/b963b0c/packages/ckeditor5-autoformat/src/inlineautoformatediting.js#L150), up to the cursor. Without seeing what is after the cursor we cannot solve the problem of stopping the formatting inside the longer word. This also explains why reversed autoformatting cannot work right now.

The first idea that comes to mind is to grab the entire text line, then check what is after the cursor. If we can find a matching delimiter, followed by whitespace or punctuation, that's great - let's format that, otherwise stop.

Looking ahead only up to the end of the line should stop autoformatting from getting too excited about formatting what's further down in the text :)

**Comment by maxbarnas** [comment]
Two things I noticed already:

*   With text like `a _b_ d^` (which had the autoformatting undone) every time I type something, I still that `_b_` autoformatted. 
    *   I am thinking about limiting the scope for autoformatting, nothing concrete yet, unfortunately.
*   [Calculation](https://github.com/ckeditor/ckeditor5/blob/b963b0c/packages/ckeditor5-autoformat/src/inlineautoformatediting.js#L103) done on the regex match doesn't like the non-capturing groups I used for matching whitespace (and later punctuation). 
    *   I can change Autoformatter to expect 5 groups instead of 3: 2 groups for separator matches (whitespace/punctuation), 2 groups for delimiters, and 1 group for content.
    *   Or maybe work with the code I have now - still trying to figure it out.

**Comment by maxbarnas** [comment]
At the moment, we expect to have space preceding the opening delimiter (`_`, `*`, `__` and `**`). Only then we allow the autoformat to do its job.

Achieving reverted autoformatting starts pretty easy, but, in connection with undo, gets complicated quite fast.

To properly format a reverted case, we have to look ahead of the cursor, possibly up to the end of the line. This breaks undo and makes undone autoformatting format again. We could look ahead and behind the cursor up to a certain point, e.g. first opened/closed delimiter, but the implementation of that becomes too complex for the scope of this bug.

**Comment by Echecivuole** [comment]
Hello all, is there so any final solution to fix this italic issue with ckeditor5?

**Comment by aniketdeotale** [comment]
Hello, I have the same issue in the project
Input : 'Test_comment_new"
Output : Test_comment_new
where comment is in itallic

is there any solution for the same?

**Comment by maxbarnas** [comment]
@Echecivuole and @aniketdeotale the issue is already fixed. Please update your CKEditor package.

**Comment by Echecivuole** [comment]
> @Echecivuole and @aniketdeotale the issue is already fixed. Please update your CKEditor package.

Hi thanks! Sorry I would need your help on from where and how update my CKEditor package. I have folder in my vendor locale. thanks!

**Comment by aniketdeotale** [comment]
> @Echecivuole and @aniketdeotale the issue is already fixed. Please update your CKEditor package.

The issue still persist for me even after updating the ckeditor to latest version . Please verify once.

**Comment by rcole1919** [comment]
Hi! There is another problem.

**Comment by rcole1919** [comment]
Hi! There is another problem.
In the admin side I am writing word and doing italic for a part of the word like:

som_eth_ing

But on the client side this text look like:

som_eth_ing

It is happenning because in the part of the word it expects only asterisks symbols

**Comment by rcole1919** [comment]
Hi! There is another problem.
In the admin side I am writing word and doing italic for a part of the word like:

som*eth*ing

But on the client side this text look like:

som_eth_ing

It is happenning because in the part of the word it expects only asterisks symbols
