### ISSUE TITLE
Font styles for list bullets/numbers

### ISSUE THREAD

**Issue by pshurygin** [ckeditor/ckeditor5#5752]
## 📝 Font styles for list bullets/numbers

At this moment there is no way to change list numbering or bullets color/font-style/font-weight etc. So when the user changes styles of text within list item (like color), the color of the numbers/bullets does not change(and there is no other way to change it).

This problem has been very frustrating for our users. I see several possible solutions for this:
1. Add some functionality to Font plugins to recognize lists in selection and apply styles to them.
2. Add some functionality to List plugins to allow setting font color/size etc in a new UI.
3. Add a new feature with a new separate interface to apply list font styles

I would say that the preferred approach is 1. but i guess it could be complicated to implement.
Also, in the meantime if there are no plans to implement this in the near future i would appreciate some advice on how to approach this problem, so that I could probably implement a new plugin for this on my own.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Do you expect that people should be able to set the style themselves? Or should it be inherited from the following text? I think that some editors do the latter.

**Comment by pshurygin** [comment]
Ideally styles should be inherited from text, but the problem here is that text inside list item may consist of multiple parts with different styles(first word is white, second is black), so it's not exactly clear on what style to inherit. 
We could probably always use the first found child styles, and it would be good enough for the most cases.
Setting styles by user is less obvious and user-friendly approach, but if it's more feasible to implement it's also an option which is better than nothing.

**Comment by ClaudiaDV** [comment]
this issue was solved or exist some plugin to fix that? I have the same error, I want to change the  styles  list from style text

**Comment by radhikaa90** [comment]
Same for me. Any update on this?

**Comment by Technopark95** [comment]
Any update on this, still not being able to color the Li Bullet in Ckeditor 37.0.1

**Comment by secret-knight** [comment]
This would be great to have, users of the product I work on are specifically asking for this functionality. At least for now, an alternative to including it out of the box in newer versions would be a snippet that we can use directly in the onReady function. This would much appreciated if doable

**Comment by Witoso** [comment]
We were discussing this quite recently, and from the technical and UI perspective this will be very challenging. While GDoc, and Word operate on pure `canvas` elements, we have to accept the semantics of HTML and default styles. Some ideas appeared to dynamically pull content styles of lists' children but it would require developing some heuristics for multiple styles. A PoC from @pszczesniak: https://codepen.io/piotrekszczesniak/pen/xxBXbEN

**Comment by spacelist-ca** [comment]
Commenting to bring more attention for this issue :) 

This is especially problematic with sizing. There are cases where the number for the list item is one font size and the list item itself is another size. 

Any more insight into workarounds to always have them be the same? It seems like a rare edge case someone will want to have the document list number be different than the items font itself. no?

**Comment by spacelist-ca** [comment]
@Witoso Any updates? If we wanted to enforce that the numbered list styling to always match that of the numbered list item,  is there a known method for that so we avoid having conflict with the default styles? This is a pretty huge flaw that should be addresses as a priority IMO.

**Comment by emiliano-ponce** [comment]
For anyone else who has this issue here is the workaround I implemented. It might help get you started if you're lost. It only applies the styles of the first text node in a list item.

Custom plugin, add this to the list of plugins for your CKEditor instance:
```
import { Editor, Plugin } from '@ckeditor/ckeditor5-core'
import {
  DowncastConversionApi,
  DowncastDispatcher,
  UpcastDispatcher,
  UpcastElementEvent,
} from '@ckeditor/ckeditor5-engine'

export default class CustomAttributes extends Plugin {
  init() {
    const editor = this.editor

    // Extend listItems to accept style attribute
    this.setupCustomAttributeConversion('li', 'listItem', 'style', editor)
  }

  setupCustomAttributeConversion(
    viewElementName: string,
    modelElementName: string,
    viewAttribute: string,
    editor: Editor
  ) {
    // In our case the attributes will just be the same
   // you can pass in the modelAttribute name you want or just prepend/append something to the viewAttribute
    const modelAttribute = viewAttribute

    // Extend the existing model schema
    editor.model.schema.extend(modelElementName, { allowAttributes: [modelAttribute] })

    // Add custom upcast conversion
    editor.conversion
      .for('upcast')
      .add(this.upcastAttribute(modelElementName, viewElementName, viewAttribute, modelAttribute))
    
    // Add custom downcast conversion
    editor.conversion.for('downcast').add(this.downcastAttribute(modelElementName, viewAttribute, modelAttribute))
  }

  upcastAttribute(
    modelElementName: string,
    viewElementName: string,
    viewAttribute: string,
    modelAttribute: string
  ): (dispatch: UpcastDispatcher) => void {
    return (dispatcher: UpcastDispatcher): void =>
      dispatcher.on<UpcastElementEvent>(`element:${viewElementName}`, (evt, data, conversionApi) => {
        const { viewItem, modelRange, modelCursor } = data

        if (!viewItem.hasAttribute(viewAttribute)) {
          return
        }

        // Get the attribute value
        const attributeValue = viewItem.getAttribute(viewAttribute)

        if (!modelRange) {
          console.error('Model range not found!')
          return
        }
        let modelElement = modelRange.start.nodeAfter
        if (!modelElement || !modelElement.is('element', modelElementName)) {
          if (modelRange.start.parent.is('element', modelElementName)) {
            modelElement = modelRange.start.parent
          } else if (modelCursor.parent.is('element', modelElementName)) {
            modelElement = modelCursor.parent
          } else {
            const walker = modelRange.getWalker()
            for (const { item } of walker) {
              if (item.is('element', modelElementName)) {
                modelElement = item
                break
              }
            }
          }
        }

        if (!modelElement) {
          console.error('Model element not found')
          return
        }

        conversionApi.writer.setAttribute(modelAttribute, attributeValue, modelElement)
      })
  }

  downcastAttribute(
    modelElementName: string,
    viewAttribute: string,
    modelAttribute: string
  ): (dispatch: DowncastDispatcher) => void {
    return (dispatcher): void =>
      dispatcher.on(
        `attribute:${modelAttribute}:${modelElementName}`,
        (evt, data, conversionApi: DowncastConversionApi) => {
          const modelElement = data.item

          // Get view element that corresponds to the model element
          const viewElement = conversionApi.mapper.toViewElement(modelElement)

          if (!viewElement) {
            console.warn('View element not found for model element', modelElement)
            return
          }

          if (data.attributeNewValue === null) {
            conversionApi.writer.removeAttribute(viewAttribute, viewElement)
          } else {
            conversionApi.writer.setAttribute(viewAttribute, data.attributeNewValue, viewElement)
          }
        }
      )
  }
}
```

Update list item styles when text styles change. You can set this up in the plugin or somewhere else in your code:
```
editor.model.document.on('change:data', () => {
          updateListParents()
})

function updateListParents() {
          const root = editor.model.document.getRoot()
          if (!root) return
          const range = editor.model.createRangeIn(root)
          const listItemTextNodes: Text[] = []
          const processedParents: Element[] = []
          for (const value of range.getWalker()) {
            const { item } = value
            if (item.is('$textProxy') && item.parent?.is('element', 'listItem')) {
              // Prevents the same parent listItem from being modified by subsequent text nodes
              if (!processedParents.includes(item.parent)) {
                listItemTextNodes.push(item.textNode)
                processedParents.push(item.parent)
              }
            }
          }
          editor.model.change(writer => {
            listItemTextNodes.forEach(textNode => {
              const parent = textNode.parent as Element

              // Add your [modelAttributeKey]: StyleSelector entries for each style you want to listenFor/apply
              const textAttrToStyleMap: Record<string, string> = {
                fontColor: 'color',
                fontFamily: 'font-family',
              }
              const styleArr: string[] = []
              for (const [attr, style] of Object.entries(textAttrToStyleMap)) {
                const value = textNode.getAttribute(attr)
                if (value) styleArr.push(`${style}: ${value}`)
              }
              if (styleArr.length > 0) {
                const style = styleArr.join('; ')
                writer.setAttribute('style', style, parent)
              } else if (parent.hasAttribute('style')) {
                writer.removeAttribute('style', parent)
              }
            })
          })
        }
```

**Comment by Witoso** [comment]
Hey everyone, we are beginning the research on this topic with @mmotyczynska. Stay tuned!

**Comment by Witoso** [comment]
Resolved in: #18537
