### ISSUE TITLE
Allow to set what the internal site is with `addTargetToExternalLinks`

### ISSUE THREAD

**Issue by robclancy** [ckeditor/ckeditor5#6491]
The content we write doesn't get published to the domain we are writing the content on. So the `addTargetToExternalLinks` (https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links) option is wrong. If we wanted to link to our current domain it should be `_blank` and linking to the actual published site shouldn't. 
Actually I just checked the code... all it does is check for `https?`. https://github.com/ckeditor/ckeditor5-link/blob/master/src/linkediting.js#L23

So it doesn't even work as it's described, it's actually "add target to absolute links".

We just wanted to set the option as external by default as a quick fix but that is just sitting there "nice to have" https://github.com/ckeditor/ckeditor5/issues/6031. And since this doesn't even check domains I would very much rather have this simple option as a workaround. Otherwise we will just have to force everything external and not allow any editing of it.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@robclancy have you tried to explicitly provide `config.link.decorators.addTargetToExternalLinks.callback` that matches all the domains that you need? That should solve the problem.

**Comment by robclancy** [comment]
For this request I guess that makes sense, so will close this. It doesn't really resolve our issues though because this option doesn't work when you have the manual new tab decorator working.
