### ISSUE TITLE
Webpack5 (symfony encore 1.0.1) / CKEditorWebpackPlugin

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5#8950]
## Provide a description of the task
Using symfony/webpack-encore v1.0.1
Throw: _Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`)_

## 📃 Other details
I think this is because CKEditorWebpackPlugin is not yet ready for Webpack 5, but first am I right ? Then if I, will it be ?

I used Webpack 4 / encore and the configuration mentioned in the doc before. I keep the same config for now.

* Browser: Firefox (not relevant)
* OS: Win10 under WSL2
* CKEditor version

        "@ckeditor/ckeditor5-adapter-ckfinder": "^25.0.0",
        "@ckeditor/ckeditor5-autoformat": "^25.0.0",
        "@ckeditor/ckeditor5-basic-styles": "^25.0.0",
        "@ckeditor/ckeditor5-block-quote": "^25.0.0",
        "@ckeditor/ckeditor5-build-classic": "^25.0.0",
        "@ckeditor/ckeditor5-code-block": "^25.0.0",
        "@ckeditor/ckeditor5-core": "^25.0.0",
        "@ckeditor/ckeditor5-easy-image": "^25.0.0",
        "@ckeditor/ckeditor5-editor-classic": "^25.0.0",
        "@ckeditor/ckeditor5-essentials": "^25.0.0",
        "@ckeditor/ckeditor5-heading": "^25.0.0",
        "@ckeditor/ckeditor5-image": "^25.0.0",
        "@ckeditor/ckeditor5-link": "^25.0.0",
        "@ckeditor/ckeditor5-list": "^25.0.0",
        "@ckeditor/ckeditor5-mention": "^25.0.0",
        "@ckeditor/ckeditor5-paragraph": "^25.0.0",
        "@ckeditor/ckeditor5-select-all": "^25.0.0",
        "@ckeditor/ckeditor5-theme-lark": "^25.0.0",

**Comment by kl3sk** [comment]
Note: Encore 1.0.2 is out with some fixes, but Ckeditor errors remains.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. Does it mean that this issue is solved and we can close it?

**Comment by kl3sk** [comment]
Hi, because ckeditor is now (about 2 hours ago ^^) compatbile with webpack5, this is not a problem anymore.


But I still have a problem with PostCCS loader following the [doc](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-encore) when upgrading to `"postcss-loader": "^5.0.0",`.

```
> dev-server-hot
> encore dev-server --public http://localhost:8080 --hot --host 0.0.0.0 --progress

Running webpack-dev-server ...

 WARNING  Be careful when using Encore.configureLoaderRule(), this is a low-level method that can potentially break Encore and Webpack when not used carefully.
<i> [webpack-dev-server] Project is running at http://localhost:8080/
<i> [webpack-dev-server] Content not from webpack is served from /home/ghoussais/tcket/public
<i> [webpack-dev-server] 404s will fallback to /index.html
<i> [webpack-dev-server] Broadcasting "http" with subtype of "webpack" via ZeroConf DNS (Bonjour)
10% building 0/1 entries 0/0 dependencies 0/0 modulesListening on port: 8080
92% sealing asset processing CKEditor5Plugin[CKEditorWebpackPlugin] Warning: The plural form function for the 'en' language has not been set.
99% done plugins FriendlyErrorsWebpackPlugin ERROR  Failed to compile with 1 errors
                                  3:18:24 PM

 error  in ./node_modules/@ckeditor/ckeditor5-basic-styles/theme/code.css

ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }


webpack compiled with 88 errors
```

**Comment by pomek** [comment]
The guide assumes that you will use `postcss-loader@3`. As I can see, you use `@5`, so you need to adjust the configuration a little bit:

```js
	.addLoader( {
		test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
		loader: 'postcss-loader',
		options: {
			postcssOptions: styles.getPostCssConfig( {
				themeImporter: {
					themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
				}
			} )
		}
	} )
```

instead of 

```js
    .addLoader({
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
        loader: 'postcss-loader',
        options: styles.getPostCssConfig( {
            themeImporter: {
                themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
            }
        } )
    } )
```

**Comment by pomek** [comment]
PostCSS options must be wrapped into an additional object called `postcssOptions`. It was introduced in the 4.0.0 release (https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0)

> PostCSS (`plugins`/`syntax`/`parser`/`stringifier`) options was moved to the `postcssOptions` option, please look at [docs](https://github.com/webpack-contrib/postcss-loader#postcssoptions)

**Comment by kl3sk** [comment]
Looking for solutions, that's what I done. Thanks for your confirmation. I can close now.

Nota: I'am not sur it is related, but I have one more error. `[CKEditorWebpackPlugin] Error: No translation has been found for the all language`

If not close this issue and redirect me to the right place.

Thanks again for all your work

**Comment by pomek** [comment]
cc: @ma2ciek ☝️

**Comment by fliespl** [comment]
@ma2ciek 

I can confirm there is an issue with translations.

Narrowed it down to 		`if ( !fs.existsSync( pathToTranslationDirectory ) ) {`

where pathToTranslationDirectory is resolved as: `/ckeditor5-core`. Shouldn't it be full path?

**Comment by fliespl** [comment]
Scratch my last comment. I didn't import @ckeditor inside js file and that's why translations weren't found - all good here :)

**Comment by ma2ciek** [comment]
> Scratch my last comment. I didn't import [**@ckeditor**](https://github.com/ckeditor) inside js file and that's why translations weren't found - all good here :)

I just tried to reproduce it and I failed. So that's probably why I failed :). Perhaps the error message could be improved in such a case. I'll create a follow-up.

**Comment by fliespl** [comment]
@ma2ciek Yeap, makes sense to provide better error message :)

I was scratching my head for an hour and gave up on this error and went ahead with english translation - I was surprised that after import polish lang started working and warning went away.

@ma2ciek On the side note - docs mention that I need custom build to work around CSP unsafe-inline (must not be allowed in our case) by extracting CSS. I used encore for example and I don't see CSP errors after such build - this one part of the documentation could also be a bit better, cause is confusing :)

`Use an editor build with the styles extracted to a separate .css file (no style-loader).`

**Comment by ma2ciek** [comment]
> [**@ma2ciek**](https://github.com/ma2ciek) On the side note - docs mention that I need custom build to work around CSP unsafe-inline (must not be allowed in our case) by extracting CSS. I used encore for example and I don't see CSP errors after such build - this one part of the documentation could also be a bit better, cause is confusing :)

I don't know what encore does under the hood, but maybe it extracts CSS by default? If that is not a case, could you report a separate issue? Or maybe something has changed in webpack 5 in this matter.

**Comment by ma2ciek** [comment]
> Looking for a solutions, that's what I finally do. Thanks for your confirmation. I can close now.
> 
> Nota: I'am not sure if it is related, but I have one more error. `[CKEditorWebpackPlugin] Error: No translation has been found for the all language`

[**kl3sk**](https://github.com/kl3sk), AFAIK it should work with when the latest `ckeditor5-dev` packages are used. This is a slightly different error.
