### ISSUE TITLE
CKEditorWebpackPlugin with Webpack5

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5#9022]
## 📝 Provide detailed reproduction steps (if any)

SymfonyWebpackEncore is out with Webpack5 update, but Ckeditor5 raise lots of tralations errors  related. Any chance A webpack5 upgrade available soon ?

More details here: https://github.com/symfony/webpack-encore/issues/683

### ✔️ Expected result

No more `Cannot find the CKEditor 5 core translation package (which defaults to '@ckeditor/ckeditor5-core').`
and any error output

Thanks

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Kocal** [comment]
Hi, please see #8213

**Comment by pomek** [comment]
We've just released a new version of the [`@ckeditor/ckeditor5-dev-webpack-plugin`](https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-webpack-plugin) package that supports both webpack versions – 4 and 5. Could you check to confirm that it works for you?

**Comment by kl3sk** [comment]
Work for webpack 5 but still have the message:

![image](https://user-images.githubusercontent.com/2953145/111594094-eaf4fe00-87ca-11eb-92ed-6d465e77167f.png)

**Comment by pomek** [comment]
cc: @ma2ciek ☝️

**Comment by ma2ciek** [comment]
I'll take a look at this one. Maybe something does not work correctly with the webpack dev server.

**Comment by kl3sk** [comment]
FYI this is my current config, maybe I've errors:

```js
    .addPlugin(new CKEditorWebpackPlugin({
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'fr',
        outputDirectory: 'assets/js/ckeditor5-translations',
        // translationsOutputFile: 'ckeditor-translation.js',
        additionalLanguages: ['all'],
        // buildAllTranslationsToSeparateFiles: true,
        addMainLanguageTranslationsToAllAssets: true,
        // strict: true,
        verbose: !Encore.isProduction(),
    }))

```

**Comment by ma2ciek** [comment]
It looks like you have misconfigured the plugin. It should be like the following:

```
.addPlugin(new CKEditorWebpackPlugin({
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'fr',
        outputDirectory: 'assets/js/ckeditor5-translations',
        // translationsOutputFile: 'ckeditor-translation.js',
        additionalLanguages: 'all', // Note that the `[]` aren't present for the `all` configuration.
        // buildAllTranslationsToSeparateFiles: true,
        addMainLanguageTranslationsToAllAssets: true,
        // strict: true,
        verbose: !Encore.isProduction(),
    }))
```

**Comment by kl3sk** [comment]
Thanks @ma2ciek this right, but have now an other warning if if config this way.

```js
    .addPlugin(new CKEditorWebpackPlugin({
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'fr',
        outputDirectory: './assets/js/ckeditor5-translations',
        // translationsOutputFile: 'ckeditor-translation.js',
        additionalLanguages: ['fr', 'en'],
        // buildAllTranslationsToSeparateFiles: true,
        addMainLanguageTranslationsToAllAssets: true,
        // strict: true,
        verbose: !Encore.isProduction(),
    }))
```

![image](https://user-images.githubusercontent.com/2953145/111766885-58299180-88a6-11eb-847f-707904329743.png)

**Comment by ma2ciek** [comment]
Hm. I feel that it might be a small issue. But it should work anyway.

**Comment by kl3sk** [comment]
Yes my `fr` language looks working.

**Comment by ma2ciek** [comment]
> FYI: with `'all'` a lot of warning drops.

Do you mean that some warnings have started appearing? Or that they have stopped?

**Comment by kl3sk** [comment]
Sorry, they appears.

**Comment by ma2ciek** [comment]
Could you show them?

**Comment by kl3sk** [comment]
I can't show to you all of them because of their huge number but here is a sample:

This is the tail with the (I think) `kk` locale, but I suppose it is the same for `all` locales.

![image](https://user-images.githubusercontent.com/2953145/111771471-097ef600-88ac-11eb-87b4-419b0ed9e474.png)

**Comment by ma2ciek** [comment]
AFAIK we don't support the `kk` language yet for most of the projects. The translations are gathered from [https://www.transifex.com/ckeditor/ckeditor5](https://www.transifex.com/ckeditor/ckeditor5) and are provided by the community.

**Comment by kl3sk** [comment]
The `kk` lanague doesn't matter for me but, a lot of other locale do the same. At least I only need 'fr' and 'en' for now. This was just for information.

**Comment by ma2ciek** [comment]
Thanks.

Perhaps we could display that information in a simplified and not so aggressive/cluttered way.

E.g. `[CKEditor5WebpackPlugin] Warning: The 'xx' langauge misses 45 translations.`

**Comment by kl3sk** [comment]
Yes a smaller not agressive warning should suffice. 

And with time. Missing translations should be updated. 

Thanks for your help and your amazing work.

**Comment by ma2ciek** [comment]
I extracted the follow-up to #9303 and I'm closing this one.
