### ISSUE TITLE
Only the first level from a multileveled list is pasted into the editor

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5#956]
## Is this a bug report or feature request? 

🐞 Bug report  

## 💻 Version of CKEditor

CKEditor 5 Developer Preview (v1.0.0-beta.2)

## 📋 Steps to reproduce

1. Create a nested list in Google docs:
![image](https://user-images.githubusercontent.com/128755/38568769-7eaad4d8-3cb7-11e8-8fd4-8214459bfb80.png)

2. Paste it into CKEditor

## ✅ Expected result

All the levels of the multileveled list are pasted in the sidebar.

## ❎ Actual result

Only the first level from a multileveled list is pasted.

## 📃 Other details that might be useful

![](https://user-images.githubusercontent.com/31243259/38558314-5aae87b6-3cd8-11e8-9ca7-54ad949139c1.gif)

https://github.com/mozilla/notes/issues/925

**Comment by Reinmar** [comment]
Unfortunately, GDocs outputs some invalid HTML. There's `ol > ol` there and, mostlikely, the editor does not handle this gracefully:

```html
<meta charset='utf-8'>
<meta charset="utf-8">
<b style="font-weight:normal;" id="docs-internal-guid-fc08fc04-b0d3-82e2-0ae8-a28e0f2c2ad3">
   <ol style="margin-top:0pt;margin-bottom:0pt;">
      <li dir="ltr" style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
         <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">XXX</span></p>
      </li>
      <ol style="margin-top:0pt;margin-bottom:0pt;">
         <li dir="ltr" style="list-style-type:lower-alpha;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">aaa</span></p>
         </li>
         <li dir="ltr" style="list-style-type:lower-alpha;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">bbb</span></p>
         </li>
      </ol>
      <li dir="ltr" style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
         <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">YYY</span></p>
      </li>
      <ol style="margin-top:0pt;margin-bottom:0pt;">
         <li dir="ltr" style="list-style-type:lower-alpha;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ccc</span></p>
         </li>
      </ol>
      <li dir="ltr" style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
         <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ZZZ</span></p>
      </li>
   </ol>
</b>
```

**Comment by Reinmar** [comment]
Just to make it easier – that's the structure I've been pasting:

![image](https://user-images.githubusercontent.com/156149/38576618-e8f32f56-3cfe-11e8-8c23-9588b27c8658.png)

**Comment by scofalik** [comment]
Yes `ol > ol` will be skipped: https://github.com/ckeditor/ckeditor5-list/blob/master/src/converters.js#L416-L427

It sucks that GDocs create such output because blame is on us then. We can try to handle such situations.

**Comment by Reinmar** [comment]
Haha ;) Wait for Word. It's a different level of mess.

**Comment by Reinmar** [comment]
@mlewand Do you remember that quote we had in CKEditor 4 docs about how bad Word's output is?

**Comment by AnnaTomanek** [comment]
> HTML exposed by Microsoft Word does not comply to any imaginable rules. It is a poetry of what can be done wrong. 

This statement is a highlight of our docs :)
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_pastefromword.html

**Comment by mlewand** [comment]
Yes the quote provided by @AnnaTomanek is the best one. Looks like MS Word is not the only app producing markup like that.

The worst cases I remember were on IE11, which attempted to "normalize" Word HTML, and did not expose `text/html` data transfer an [example list markup produced by Word+IE11 combo can be seen here](https://codepen.io/mlewand/pen/VXRyJm?editors=1000#0). Gotta love these `b` directly in `ol`, nested (unclosed) paragraphs - all the good stuff.

**Comment by Jack-s** [comment]
It looks like this is still an issue, at least with word. It also appears that in CKEditor 4 it does work.
[template with bullet levels.docx](https://github.com/ckeditor/ckeditor5/files/3241568/template.with.bullet.levels.docx)

https://ckeditor.com/ckeditor-4/demo/  --Works

https://ckeditor.com/ckeditor-5/demo/ --Doesn't work

**Comment by mlewand** [comment]
Actually this issue has been fixed in [v12.4.0](https://ckeditor.com/blog/CKEditor-5-v12.4.0-with-image-resizing-to-do-lists-RTL-language-support-and-more/).

You can give it a try here: https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html

**Comment by Jack-s** [comment]
Sorry but it doesn't look like it is actually fixed. I just tried the link you posted with the attached word file and it still doesn't work. It does paste part of the text from the nested list but not formatted as another list and doesn't paste the text from the third level list at all.

**Comment by Reinmar** [comment]
@Jack-s This is a separate issue – CKEditor 5 does not support yet pasting nested lists from Word (https://github.com/ckeditor/ckeditor5-paste-from-office/issues/19).

In this ticket, we worked on content disappearing when pasting an incorrectly formatted (in terms of HTML rules) list structure. Such incorrect list structures are created by e.g. Google Docs, Gmail or Evernote.

Support for pasting lists from Word is something different because Word doesn't even produce any reasonable markup for lists. It's a manual job of picking information from a garbage "HTML".

**Comment by Jack-s** [comment]
@Reinmar OK thanks, but what about the content that "disappears" from word as well (the third indentation level)? Not sure if it needs to be fixed independently of the general "paste from office" feature.

**Comment by mlewand** [comment]
@Jack-s This is still a separate issues, the two cases are unrelated to each other that's why should be tracked separately. Feel free to subscribe ckeditor/ckeditor5-paste-from-office#19 to get further updates.
